### PR TITLE
FEATURE: add a "repo import into editor projects" command to new toolkit

### PR DESCRIPTION
**Pull request by amtoine**
This comes from my [`kickstart.nvim` config](https://github.com/goatfiles/kickstart.nvim/blob/master/toolkit.nu#L22-L48).

because `nu-git-manager` will manage a bunch of `git` repos, i think having a little tool to load all of them at once in a "projects manager" is nice.

this PR:
- adds a `toolkit.nu` module to `nu-git-manager`
> **Note**
> such a module can be loaded automatically upon entering the root of the repo locally with an [`env_change` hook](https://github.com/goatfiles/dotfiles/blob/nightly/.config/nushell/lib/core/hooks.nu#L20-L32)
- adds a bit of completion to it
- adds the `--into` option which now supports *neovim*
- adds `FIXME`s to not forget about the `ghq` dependency

### CODE REVIEW

**Comment by melMass** [comment]
What do you think about having a global config file for git-manager?

One of the config options could be `project`, a dict of paths.

Either that or we should handle the cross platform default paths if they exist, it's the first time I hear about `project_nvim/project_history`, but `.share` is not the same on mac or windows

**Comment by amtoine** [comment]
@melMass
i've asked in https://github.com/ahmedkhalf/project.nvim/issues/113 :wink:

**Comment by melMass** [comment]
> how would you write that in that case?

Well we are in nu so I would vote for going the $nu.config way. I don't think we can mimic the new nested mutable version of the last nushell, but basically as it was before. So in the env.nu or whatever as nu.config, and in repl we could add utilities to manipulate it (a bit like my add-path) :

```nu
let-env git_config = ( $env.git_config | merge { use_sugar:false } )
```

> i'd say we can replace .local/share with XDG_DATA_HOME?
Then I think it's just not "cross platform" oob, one can set xdg but it does not exist in either mac or win.

image
I'd say it could be part of the default config of nu-git-manager as XDG_DATA_HOME only if found.

**Comment by amtoine** [comment]
> ```nu
> let-env git_config = ( $env.git_config | merge { use_sugar:false } )
> ```
> 
kinda like that :smirk: 

> I'd say it could be part of the default config of nu-git-manager as XDG_DATA_HOME only if found.
>
yeah we could have a bunch of things to look at
- config
- environment variable
- CLI option
- default value

**Pull request merged**
