### PR TITLE
refactor the CI in scripts

### PR DESCRIPTION
**Pull request by amtoine**
related to
- https://github.com/nushell/nupm/pull/37

well, that's basically the exact same thing as in https://github.com/nushell/nupm/pull/37 :wink:

### CODE REVIEW

**Comment by melMass** [comment]
Nice, I like the idea, I have the exact same comments as the linked PR 😋 ! 
Why not use nu? 
I'm currently exploring that path myself, a combo of justfile and nu scripts for CIs

**Comment by amtoine** [comment]
this is to use the latest revision of Nushell, but i'm wondering if we could just use the latest stable release and upgrade once in a while when the language breaks :thinking:

**Comment by amtoine** [comment]
i'll try that in another PR

**Comment by melMass** [comment]
> this is to use the latest revision of Nushell, but i'm wondering if we could just use the latest stable release and upgrade once in a while when the language breaks :thinking: 

I think we mentionned that but I'm more enclined to target release than nightly in general

**Comment by amtoine** [comment]
> I think we mentionned that but I'm more enclined to target release than nightly in general
>
we can bring that question back to the table the day the CI using stable releases fails :wink:

**Comment by melMass** [comment]
I'm not sure to understand all the CI PRs but I think we can close this in favor of #37

**Pull request closed without merging**
